name: "Setup HashiCorp Releases"
description: "Download and setup binary from releases.hashicorp.com in a GitHub Actions build environment"
author: "Bloomin' Labs"
inputs:
  package:
    description: "Name of the package to install"
    required: true
  version:
    description: "Version of the package to install, or 'latest' (default). This accepts semver ranges like ^3.0.0."
    required: true
    default: "latest"
  license_class:
    description: "License class to filter releases to. Either 'enterprise' or 'oss' (default). See the hashicorp releases API for more details (https://releases.hashicorp.com/docs/api/v1/#operation/listReleasesV1)."
    default: "oss"
  include_prerelease:
    description: "Should prerelease versions be considered when resolving the semver version. defaults to false"
    default: false
branding:
  icon: "terminal"
  color: "purple"
runs:
  using: "node16"
  main: "dist/setup/index.js"
  post: "dist/cache-save/index.js"
